### ISSUE TITLE
Can't use pydealer from Python3

### ISSUE THREAD

**Issue by MickaelG** [Trebek/pydealer#18]
I have installed pydealer using pip. It works well using python2. However, when I try to use it using python3, I have the following error:
AttributeError: 'module' object has no attribute 'Deck'
    >>> import pydealer
    >>> dir(pydealer)
    ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', __path__', '__spec__']

**Comment by Trebek** [comment]
That's not the full error traceback message is it? If not, could you possibly post the whole message? That way I can actually see where the error is occurring.

I will also test the package myself. I usually use Python 2.7, and to be honest, haven't really tested this package too thoroughly with Python 3. I guess I'm going to have to do that (should have done that already).

You can also try downloading and installing the ['dev' version](https://github.com/Trebek/pydealer/tree/dev), which is fully functional, but may have a bug here or there. It is partially updated, and has been changed around quite a bit. It's possible that the issue you're having isn't an issue any more - or, conversely, that there are even more problems. I hope not though. If you want to try it out, [click here](https://github.com/Trebek/pydealer/archive/dev.zip) to download it.

I haven't really worked on this package in a while - life getting in the way - but I will take a look at it, and see if I can iron this bug out. If I can't, maybe someone else can.

**Comment by Trebek** [comment]
Committed the latest changes to the [dev branch](https://github.com/Trebek/pydealer/tree/dev). I think this is the push that I'll actually release. Try it out, see if it works for you. I tried it, using Python 3.2 (I know that is an old version, but it's what was on the computer I was using), and it seemed to work fine when I toyed with it. Passed all of the 98 tests, in the tests folder as well. I figure it should still probably work in the later versions of Py3.

If not, let me know. Sorry for my sloppy testing practices. This is just a hobby for me, and I am far from professional.

**Comment by MickaelG** [comment]
It works perfectly fine with last version. Thanks for the update and the useful software.

**Comment by Trebek** [comment]
Very glad to hear that! And you are welcome. Glad someone has found it useful in some way.

And actually, I should probably be thanking you, for bringing this to my attention, and giving me motivation to update this little package. I had neglected it for many months before the update. So thanks!
