### ISSUE TITLE
Multiple Deck options?

### ISSUE THREAD

**Issue by cguethle** [Trebek/pydealer#19]
Any thoughts on supporting a multiple deck feature?  I'm looking at doing a blackjack sort of simulator, but want to have a dealer that has done a multiple deck shuffle (e.g. double deck BJ, 6 pack, 8 pack, etc).

Thanks!

**Comment by cguethle** [comment]
And I just took the time to look at your source, noticing the **add** on Deck that would let me do this easily.  Assuming the following is true.

```
double_deck = Deck() + Deck()
double_deck.shuffle()
```

That would work you think?

**Comment by Trebek** [comment]
That would create two separate decks, combine them into one, and then shuffle it. If that is what you're looking to do, then yes, that should work. You can combine as many decks (or stacks) as you want.

You could do something like:

```
six_pack_deck = Deck()

for _ in range(5):
    six_pack_deck += Deck()
```

or better yet, throw it into a little function:

```
def multi_deck(num):
    deck = Deck()
    for _ in range(num):
        deck += Deck()
    return deck
```

Perhaps I'll add a little method to the Deck class to make multi decks even easier. Maybe when instantiating a new Deck, you could specify how many decks the deck should contain.

**Comment by cguethle** [comment]
Yeah, that is what I want to do, a multi deck deck.  A multi deck class method would be useful for that purpose as you say.  Something like the following (haven't tested, mileage may vary)...

``` python
@classmethod
def multi_deck(cls, number_of_decks, **new_deck_args):
    """
    Generates a Deck made up of multiple decks, returning a new Deck with them combined and shuffled.
    :param number_of_decks: The number of Decks to use when constructing the larger Deck.
    :return: A new Deck constructed of a number of Decks as specified by number_of_decks.
    :rtype: Deck
    """
    new_decks = [Deck(**new_deck_args) for _ in xrange(number_of_decks)]

    return sum(new_decks)
```

**Comment by Trebek** [comment]
Never thought of trying to use the sum function on a list of Decks. Just tested it out, and it throws an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'Deck'
```

So apparently the sum function won't work for this.

I think just making it so you could instantiate a deck containing multiple packs would make the most sense though anyway, instead of making a class method to do it. So you could just do something like:

```
six_pack_deck = Deck(packs=6)
```

**Comment by cguethle** [comment]
That seems good.  Honestly not getting the time to work on my little project.  So...  Nice library though.  :)

**Comment by Trebek** [comment]
No problem, and thanks!
